### ISSUE TITLE
Training Script Missing

### ISSUE THREAD

**Issue by sven-mayer** [XinArkh/VNect#11]
A training script to test possible improvements would be very sweet. I know @XinArkh already started a script but it lights of TF2.0 #10 this needs more work.

I hope to support a script for TF 2.0 soon.

**Comment by sven-mayer** [comment]
When calling `mpi_inf_3dhp.py` I get a `FileNotFoundError: [Errno 2] File b'./mpi_inf_3dhp/train.txt'` any chance you can provide the script to create the `train.txt` because after downloading the whole dataset there is no such file, or am I mistaken?

**Comment by XinArkh** [comment]
The mpi_inf_3dhp data processing part is completely recorded in [my another repository](https://github.com/XinArkh/mpi_inf_3dhp). You can get `train.txt` and `test.txt` (image indexes) by running the codes step by step with instructions. Let me know if there occur other incidents. Good luck!
