### ISSUE TITLE
Network definition error on ResNet Block

### ISSUE THREAD

**Issue by Danfoa** [XinArkh/VNect#13]
Hello, I believe there is an error in the definition of one of the ResNet Blocks, particularly on ResNet Stage2 Block C, the output activation seems to be using the previous block output (B) instead of its own.

https://github.com/XinArkh/VNect/blob/f3d1fd1db693c683134e5cd80b2bbc5fb4684b45/src/vnect_model.py#L61

I am pretty sure this is an issue and is causing that an entire identity block gets ignored.

Am I right?

**Comment by XinArkh** [comment]
Hello Danfoa, I think you are right about this issue. Thank you for your detailed check! I will fix it sooner.
