### ISSUE TITLE
关于VNect的一点疑问

### ISSUE THREAD

**Issue by Eric-1216** [XinArkh/VNect#17]
您好，我想请教一下，这个代码是您自己复现的吗？

**Comment by XinArkh** [comment]
不完全是，这个仓库的代码在实现的时候部分参考了其他人更早的VNect实现，见README的[Reference Repositories](https://github.com/XinArkh/VNect#reference-repositories)一节

**Comment by Eric-1216** [comment]
不好意思，我没有找到第一步配置环境的txt文件，请问这个文件在哪里呢？

**Comment by XinArkh** [comment]
并不能直接配置，你需要首先联系论文作者索要训练好的模型，请进一步阅读README文档

**Comment by jeffreyking23** [comment]
能把网络权重发到邮箱吗？408130533@qq.com，多谢~

**Comment by WangChenjun521** [comment]
请问能把weight发到邮箱吗？非常感谢！[cjwang21@m.fudan.edu.cn](mailto:cjwang21@m.fudan.edu.cn)
