### ISSUE TITLE
About the caffemodel and weight

### ISSUE THREAD

**Issue by panhu** [XinArkh/VNect#18]
Can you share weight and model files?I also have sent a emial to the author yesterday, but he haven't replied yet. my email is

**Comment by lj-cug** [comment]
In \models\caffe_model\readme.txt. I think it's an misspelling. The load_weights.py should be init_weights.py

**Comment by Ared521** [comment]
> Can you share weight and model files?I also have sent a emial to the author yesterday, but he haven't replied yet. my email is

Has the author provided it to you? I've been sending it for two days, and the author hasn't replied
