### ISSUE TITLE
Where is "load_weights.py" and also the caffe data

### ISSUE THREAD

**Issue by lj-cug** [XinArkh/VNect#19]
Dear Wu:
     I cannot find the `load_weights.py` in the root directroy? And also I need the pretrained caffe data. This tool is efficient and suitable for VR environment.
Thanks
Li

**Comment by XinArkh** [comment]
Can you provide more information where did you see `load_weights.py` mentioned? Maybe I should check it first. 
For trained model, please refer to https://github.com/XinArkh/VNect/issues/18#issuecomment-952649723

**Comment by XinArkh** [comment]
https://github.com/XinArkh/VNect/issues/18#issuecomment-999320691
You are right, it is supposed to be `init_weights.py`. I will fix it soon.
