### ISSUE TITLE
Could you please provide requirements.txt documents?

### ISSUE THREAD

**Issue by Mustenaka** [XinArkh/VNect#20]
Could you please provide requirements.txt documents? I want to reproduce this project.

**Comment by XinArkh** [comment]
What do you mean by requirement.txt?

If you mean model weights, please refer to: https://github.com/XinArkh/VNect/issues/18#issuecomment-952649723

**Comment by Mustenaka** [comment]
Like this issue: https://github.com/XinArkh/VNect/issues/21
I want quickly reproduce this project, and follow your README - SETUP, there is not requirements.txt file from this project, where can i get this file?

![QQ_1721789733591](https://github.com/user-attachments/assets/ce21f4ff-90a7-4cbd-85f8-d41440ac615b)

**Comment by XinArkh** [comment]
Fedora 29 environment is contributed by @yuripourre, so I do not have this file either. 
If you already possess the model weight file, you might consider skipping this step and proceeding directly to the Usage section.
