### ISSUE TITLE
ModuleNotFoundError: No module named 'caffe2pkl'

### ISSUE THREAD

**Issue by yuripourre** [XinArkh/VNect#4]
Hello, I am trying to setup the environment. I am not a python developer so I am sorry if it's a simple issue.

I could install requirements and compile caffe library but when I try to run `python3 load_weights.py` I get this error: `ModuleNotFoundError: No module named 'caffe2pkl'`.

What am I missing?

**Comment by XinArkh** [comment]
It's a python path referring issue. 
If you use pycharm, try right click `init` folder > Mark Directory as > Sources root (so as `src` and other folders if necessary...)
If you use console calling python, adding the following lines before `from init import *`:
```python
import sys
sys.path.extend(['./src', './init'])
```

I will also update a newer version of code to fix this issue later. Thank you for your feedback!
Moreover, this repo is now lack of training script of the model. Contributions are welcomed!

**Comment by XinArkh** [comment]
The code is updated. Feel free to keep commenting if there are other problems occurs.

**Comment by yuripourre** [comment]
Your update solved the problem, thank you!
