### ISSUE TITLE
One Euro Filter Issue

### ISSUE THREAD

**Issue by Hwang-dae-won** [XinArkh/VNect#6]
In the Vnect paper, it is known that the OneEuroFilter is used to control the shaking of the joint.

The result of my 3d pose estimation is too trembling. Can I reduce the vibration more by adjusting the euro filter parameter? As far as I know, I can adjust the config_3d and config_2d parameters in ./blob/master/src/estimator.py. 

What parameters should be adjusted here?

**Comment by XinArkh** [comment]
please refer to:  https://github.com/XinArkh/WX_Official_Account_Backup/blob/master/20190224_%E5%8F%AF%E8%83%BD%E6%98%AF%E5%85%A8%E7%BD%91%E5%94%AF%E4%B8%80%E7%9A%84%E3%80%8C%E4%B8%80%E6%AC%A7%E5%85%83%E6%BB%A4%E6%B3%A2%E5%99%A8%E3%80%8D%E8%AF%A6%E8%A7%A3%E7%AC%94%E8%AE%B0.pdf
