### ISSUE TITLE
Inferring - run_pic.py

### ISSUE THREAD

**Issue by fire17** [XinArkh/VNect#7]
Hey there!
VNect looks amazing and I hope to try the demo :)
I understand that before inferring the model is needed (models/caffe_model. ) ? is that correct?
So I've sent you an email like the readme suggests, hope you'll see it
Thank you very much!
Tami

**Comment by XinArkh** [comment]
Thank you for your issue. 
I am not the paper author (just a third-party developer) and haven't received your email. The caffe model is supposed to be provided by the paper author. Since you have sent your request to the paper author, please be patient for the author's reply.
