### ISSUE TITLE
3D joints (j_3d) outputs of the estimator are abosolutely different from dataset annotation

### ISSUE THREAD

**Issue by AminAnsarian** [XinArkh/VNect#9]
Hello,

I am trying to determine the accuracy of the model for comparison to my own using the same dataset. However, when feeding a frame to your model, the 3d joints outputs are absolutely different from the ground truth 3D annotations of the same frame. For example, I have used the first frame of Subject 1, Sequence 1, video_5.avi of the dataset. The ground truth of this frame is: 
-21.6287	-333.956	3135.93
-12.0565	-437.894	3159.81
-28.9552	-257.106	3118.83
-29.0008	-256.532	3118.73
-40.3666	-30.7485	3095.92
-29.5895	-511.765	3123.19
-34.8855	-597.76	3115.35
-20.7635	-767.097	3148.25
-0.807343	-476.879	3084.42
80.4458	-423.353	3062.78
351.847	-413.549	2899.33
548.15	-388.725	2754.84
622.391	-365.207	2710.91
-76.6841	-475.622	3118.22
-144.08	-443.038	3184.03
-407.988	-389.254	3351.16
-625.66	-368.391	3461.66
-702.881	-360.193	3505.98
68.4666	-29.1406	3047.41
33.4087	526.319	3065.68
51.2679	961.452	3138.23
17.8106	985.515	3045.47
5.99548	980.27	3021.36
-149.2	-32.3563	3144.43
-89.8705	523.425	3117.49
-28.2177	960.295	3133.84
-97.7287	978.96	3062.26
-115.506	970.646	3043.2

While your model, on the other hand, outputs this array, in no way comparable to the aforementioned: 
-2.24804	-647.93	145.743
33.5533	-462.836	71.606
-40.1966	-408.077	87.858
-302.668	-370.029	358.651
-509.969	-449.051	361.423
104.763	-417.754	20.1654
351.752	-285.586	186.504
431.772	-384.451	165.197
-34.0673	-11.7031	45.5164
87.6427	335.656	302.249
23.001	652.348	517.724
13.1	20.2222	-34.3508
-102.993	330.257	342.15
-32.9888	661.247	497.651
9.34312e-05	1.71045e-05	-8.16818e-06
19.1416	-203.681	42.9171
-3.12868	-533.283	74.884
-541.534	-451.382	438.98
500.622	-404.085	221.262
-169.163	644.26	543.542

**Comment by XinArkh** [comment]
In VNect, all the joint coordinates are subtracted by previs (note '0 0 0' in line 15 above). 
Also refer to this: https://github.com/XinArkh/VNect/blob/23fa81e6708181f7a098689e6f9711911e29e1ff/src/utils.py#L204-L205
Let me know if there's further confusion. Thanks.

**Comment by AminAnsarian** [comment]
> In VNect, all the joint coordinates are subtracted by previs (note '0 0 0' in line 15 above).
> Also refer to this:
> 
> https://github.com/XinArkh/VNect/blob/23fa81e6708181f7a098689e6f9711911e29e1ff/src/utils.py#L204-L205
> 
> 
> Let me know if there's further confusion. Thanks.

That is true, but even so, if you compare the two matrices, even after normalization, the output is still very different. I commented this line, and still, the output is different. I need to mention that I am running the estimator.py inside the src directory. Although it is the same code. Thank you again for your response.

**Comment by XinArkh** [comment]
1. benchmark.py is an old implementation and has not been updated for a while, though still functional for now. I recommend run_* files if convenient.
2. You should compare the results with univ_annot3 instead of annot3. (see paper for details)
3. Even so, there will also be differences among the results. Because the model is not 100% accurate.
4. The model is trained on both mpi_inf_3dhp and human3.6m, according to the paper.

**Comment by lvandoit** [comment]
hi :
may i ask you a question about the mpi-inf-3dhpdataset?such as in  the first frame of Subject 1, Sequence 1, video_5.avi of the dataset. How many human body joints are there in the mpi-inf-3dhp dataset?Why  28 lines here?But in the testing data,because there ard 17 joint,so The data is in the form of [x,17,3]. thanks for you any   

> Hello,
> 
> I am trying to determine the accuracy of the model for comparison to my own using the same dataset. However, when feeding a frame to your model, the 3d joints outputs are absolutely different from the ground truth 3D annotations of the same frame. For example, I have used the first frame of Subject 1, Sequence 1, video_5.avi of the dataset. The ground truth of this frame is:
> -21.6287 -333.956 3135.93
> -12.0565 -437.894 3159.81
> -28.9552 -257.106 3118.83
> -29.0008 -256.532 3118.73
> -40.3666 -30.7485 3095.92
> -29.5895 -511.765 3123.19
> -34.8855 -597.76 3115.35
> -20.7635 -767.097 3148.25
> -0.807343 -476.879 3084.42
> 80.4458 -423.353 3062.78
> 351.847 -413.549 2899.33
> 548.15 -388.725 2754.84
> 622.391 -365.207 2710.91
> -76.6841 -475.622 3118.22
> -144.08 -443.038 3184.03
> -407.988 -389.254 3351.16
> -625.66 -368.391 3461.66
> -702.881 -360.193 3505.98
> 68.4666 -29.1406 3047.41
> 33.4087 526.319 3065.68
> 51.2679 961.452 3138.23
> 17.8106 985.515 3045.47
> 5.99548 980.27 3021.36
> -149.2 -32.3563 3144.43
> -89.8705 523.425 3117.49
> -28.2177 960.295 3133.84
> -97.7287 978.96 3062.26
> -115.506 970.646 3043.2
> 
> While your model, on the other hand, outputs this array, in no way comparable to the aforementioned:
> -2.24804 -647.93 145.743
> 33.5533 -462.836 71.606
> -40.1966 -408.077 87.858
> -302.668 -370.029 358.651
> -509.969 -449.051 361.423
> 104.763 -417.754 20.1654
> 351.752 -285.586 186.504
> 431.772 -384.451 165.197
> -34.0673 -11.7031 45.5164
> 87.6427 335.656 302.249
> 23.001 652.348 517.724
> 13.1 20.2222 -34.3508
> -102.993 330.257 342.15
> -32.9888 661.247 497.651
> 9.34312e-05 1.71045e-05 -8.16818e-06
> 19.1416 -203.681 42.9171
> -3.12868 -533.283 74.884
> -541.534 -451.382 438.98
> 500.622 -404.085 221.262
> -169.163 644.26 543.542

**Comment by lvandoit** [comment]
> Hello,
> 
> I am trying to determine the accuracy of the model for comparison to my own using the same dataset. However, when feeding a frame to your model, the 3d joints outputs are absolutely different from the ground truth 3D annotations of the same frame. For example, I have used the first frame of Subject 1, Sequence 1, video_5.avi of the dataset. The ground truth of this frame is:
> -21.6287 -333.956 3135.93
> -12.0565 -437.894 3159.81
> -28.9552 -257.106 3118.83
> -29.0008 -256.532 3118.73
> -40.3666 -30.7485 3095.92
> -29.5895 -511.765 3123.19
> -34.8855 -597.76 3115.35
> -20.7635 -767.097 3148.25
> -0.807343 -476.879 3084.42
> 80.4458 -423.353 3062.78
> 351.847 -413.549 2899.33
> 548.15 -388.725 2754.84
> 622.391 -365.207 2710.91
> -76.6841 -475.622 3118.22
> -144.08 -443.038 3184.03
> -407.988 -389.254 3351.16
> -625.66 -368.391 3461.66
> -702.881 -360.193 3505.98
> 68.4666 -29.1406 3047.41
> 33.4087 526.319 3065.68
> 51.2679 961.452 3138.23
> 17.8106 985.515 3045.47
> 5.99548 980.27 3021.36
> -149.2 -32.3563 3144.43
> -89.8705 523.425 3117.49
> -28.2177 960.295 3133.84
> -97.7287 978.96 3062.26
> -115.506 970.646 3043.2
> 
> While your model, on the other hand, outputs this array, in no way comparable to the aforementioned:
> -2.24804 -647.93 145.743
> 33.5533 -462.836 71.606
> -40.1966 -408.077 87.858
> -302.668 -370.029 358.651
> -509.969 -449.051 361.423
> 104.763 -417.754 20.1654
> 351.752 -285.586 186.504
> 431.772 -384.451 165.197
> -34.0673 -11.7031 45.5164
> 87.6427 335.656 302.249
> 23.001 652.348 517.724
> 13.1 20.2222 -34.3508
> -102.993 330.257 342.15
> -32.9888 661.247 497.651
> 9.34312e-05 1.71045e-05 -8.16818e-06
> 19.1416 -203.681 42.9171
> -3.12868 -533.283 74.884
> -541.534 -451.382 438.98
> 500.622 -404.085 221.262
> -169.163 644.26 543.542

hi :
may i ask you a question about the mpi-inf-3dhpdataset?such as in  the first frame of Subject 1, Sequence 1, video_5.avi of the dataset. How many human body joints are there in the mpi-inf-3dhp dataset?Why  28 lines here?But in the testing data,because there ard 17 joint,so The data is in the form of [x,17,3]. thanks for you any reply.
